### ISSUE TITLE
`match` filter doesn't work with rails 5.1(.7)

### ISSUE THREAD

**Issue by jackcasey** [graphiti-api/graphiti#207]
The ActiveRecord Adaptor calls to `sanitize_sql_like` which is apparently not a supported API and has been removed at least in Rails 5.1 afaics:

I'm not sure what other versions of rails are affected, we are on 5.1.7

https://github.com/graphiti-api/graphiti/blob/a5c32ed3bb08459b7f52af9d4f2cb5ae74df438e/lib/graphiti/adapters/active_record.rb#L91

Gives:
```
NoMethodError: undefined method `sanitize_sql_like' for #<G::Grower::ActiveRecord_Relation:0x00007fd2b7f80ae8>
```

More info:
https://github.com/rails/rails/issues/28947

It appears like the fix is simple, just need to call out to a class that includes the `ActiveRecord::Sanitization` concern. 

I will try to tackle this at some point but currently just getting started with Graphiti and would need to figure out how to go about setting up a failing test for this to properly make a good PR for the issue. (BTW I'm in love with Graphiti so far, thanks so much for the awesome library).

**Comment by wadetandy** [comment]
@jackcasey I believe I fixed this issue in my pr #208. Would you be able to verify that patch fixes your issue before we release a new version?

**Comment by jackcasey** [comment]
Just for completeness in case you missed it; I replied to that PR #208. It works fine :) Thanks.

**Comment by jackcasey** [comment]
This should be fixed by #219 just forgot to close.
